### ISSUE TITLE
binder not up-to-date

### ISSUE THREAD

**Issue by wolfidan** [openradar/asean2024-pyrad-course#6]
Hi @mgrover1 ,

Sorry for bothering you but I noticed that the binder version provided by projectpythia (link on the main github page), is often not up-to-date, even though it should use the latest container. I have been having difficulties finding out why. When running the binder over mybinder it works and uses the latest version. Do you have any idea why this happens, did you experience something similar for ams and erad courses?

Thanks a lot,
Cheers,

**Comment by mgrover1** [comment]
Sorry for the delay here @wolfidan - it is because it is using the main branch and will cache that image. The key here is updating with the latest commit ID.

Check out the recent short course for an example https://github.com/openradar/ams-open-radar-2023/blob/main/binder/Dockerfile

Also, it looks like the build is failing due to a missing table of contents file - this is required, and you could add a single line specifying the inclusion of the README file.
